# Generated by Django 5.2.12 on 2026-08-03 06:16

import crm.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=crm.models.customer_code, max_length=32, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('phone_key', models.CharField(editable=False, max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('vehicle_model', models.CharField(blank=True, max_length=120)),
                ('vehicle_number', models.CharField(blank=True, max_length=30)),
                ('vin', models.CharField(blank=True, max_length=60)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('due_km', models.PositiveIntegerField(blank=True, null=True)),
                ('due_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['sequence', 'due_km'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=crm.models.technician_code, max_length=32, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('ADVISOR', 'Service advisor'), ('TECHNICIAN', 'Technician'), ('HELPER', 'Helper'), ('MANAGER', 'Service manager')], default='TECHNICIAN', max_length=15)),
                ('skills', models.CharField(blank=True, max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin / Manager'), ('STAFF', 'Staff / Employee')], default='STAFF', max_length=12)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=80)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=crm.models.lead_code, max_length=32, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('source', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('WALK_IN', 'Walk-in'), ('PHONE', 'Phone'), ('WEBSITE', 'Website'), ('REFERRAL', 'Referral'), ('SOCIAL', 'Social media'), ('OTHER', 'Other')], default='WHATSAPP', max_length=20)),
                ('stage', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('VISIT', 'Showroom visit'), ('QUOTE', 'Quotation shared'), ('BOOKING', 'Booking'), ('WON', 'Won'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('rating', models.CharField(choices=[('HOT', 'Hot'), ('WARM', 'Warm'), ('COLD', 'Cold')], default='WARM', max_length=10)),
                ('interested_model', models.CharField(blank=True, max_length=120)),
                ('preferred_color', models.CharField(blank=True, max_length=60)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('next_followup', models.DateTimeField(blank=True, null=True)),
                ('lost_reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.customer')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=crm.models.reminder_code, max_length=32, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('kind', models.CharField(choices=[('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('VISIT', 'Visit'), ('SERVICE', 'Service reminder'), ('PAYMENT', 'Payment'), ('OTHER', 'Other')], default='CALL', max_length=15)),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DONE', 'Completed'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='crm.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='crm.lead')),
            ],
            options={
                'ordering': ['status', 'due_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='source_lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_customer', to='crm.lead'),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=crm.models.quotation_code, max_length=32, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('model_name', models.CharField(max_length=120)),
                ('ex_showroom', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('central_subsidy', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('state_subsidy', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('rto_registration', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('insurance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('accessories', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to customer'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='crm.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=crm.models.service_code, max_length=32, unique=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=120)),
                ('vehicle_number', models.CharField(blank=True, max_length=30)),
                ('vin', models.CharField(blank=True, max_length=60)),
                ('odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('complaint', models.TextField()),
                ('diagnosis', models.TextField(blank=True)),
                ('work_done', models.TextField(blank=True)),
                ('technician_notes', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CHECKED_IN', 'Checked in'), ('DIAGNOSIS', 'Diagnosis'), ('APPROVAL', 'Awaiting customer approval'), ('IN_PROGRESS', 'Repair in progress'), ('READY', 'Ready for delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=15)),
                ('appointment_at', models.DateTimeField(blank=True, null=True)),
                ('promised_at', models.DateTimeField(blank=True, null=True)),
                ('estimate_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('customer_approved', models.BooleanField(default=False)),
                ('pickup_required', models.BooleanField(default=False)),
                ('next_followup', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='crm.serviceteammember')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_tickets', to='crm.customer')),
                ('service_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='crm.serviceplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CHECKED_IN', 'Checked in'), ('DIAGNOSIS', 'Diagnosis'), ('APPROVAL', 'Awaiting customer approval'), ('IN_PROGRESS', 'Repair in progress'), ('READY', 'Ready for delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=15)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='crm.serviceticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShowroomVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=crm.models.visit_code, max_length=32, unique=True)),
                ('visitor_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('visit_at', models.DateTimeField()),
                ('purpose', models.CharField(default='New vehicle enquiry', max_length=180)),
                ('interested_model', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No show'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=12)),
                ('outcome', models.TextField(blank=True)),
                ('next_followup', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showroom_visits', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showroom_visits', to='crm.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showroom_visits', to='crm.lead')),
            ],
            options={
                'ordering': ['-visit_at'],
            },
        ),
    ]
