# Generated by Django 5.2.12 on 2026-08-03 06:34

import crm.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_service_login_and_quote_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin / Manager'), ('CRM_MANAGER', 'CRM manager'), ('SALES_EXECUTIVE', 'Sales executive'), ('SERVICE_STAFF', 'Service staff'), ('STAFF', 'Staff / Employee')], default='STAFF', max_length=20),
        ),
        migrations.CreateModel(
            name='SalesTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=crm.models.sales_person_code, max_length=32, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('MANAGER', 'Sales manager'), ('CRM_MANAGER', 'CRM manager'), ('EXECUTIVE', 'Sales executive'), ('TELECALLER', 'Telecaller'), ('OTHER', 'Other')], default='EXECUTIVE', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='crm.salesteammember')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=crm.models.daily_activity_code, max_length=32, unique=True)),
                ('activity_date', models.DateField(default=django.utils.timezone.localdate)),
                ('activity_type', models.CharField(choices=[('CALL', 'Daily call'), ('BOOKING', 'Daily booking'), ('SALE', 'Daily sale'), ('SERVICE', 'Daily service completed'), ('PROBLEM', 'Problem resolved')], max_length=12)),
                ('title', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=12)),
                ('outcome', models.TextField(blank=True)),
                ('next_followup', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_activities', to='crm.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_activities', to='crm.lead')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_activities', to='crm.quotation')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_daily_activities', to=settings.AUTH_USER_MODEL)),
                ('service_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_activities', to='crm.serviceticket')),
                ('sales_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_activities', to='crm.salesteammember')),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=crm.models.work_task_code, max_length=32, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('TODO', 'To do'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Completed'), ('CANCELLED', 'Cancelled')], default='TODO', max_length=15)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='crm.salesteammember')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.lead')),
            ],
            options={
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
    ]
