# Generated by Django 5.2.12 on 2026-08-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_user_role_salesteammember_dailyactivity_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='crm_custome_name_0c497a_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['updated_at'], name='crm_custome_updated_7389ad_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyactivity',
            index=models.Index(fields=['activity_date', 'activity_type'], name='crm_dailyac_activit_8ded5c_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyactivity',
            index=models.Index(fields=['sales_member', 'activity_date'], name='crm_dailyac_sales_m_ea051f_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyactivity',
            index=models.Index(fields=['customer', 'activity_date'], name='crm_dailyac_custome_695e76_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['status', 'due_at'], name='crm_followu_status_a1053c_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['assigned_to', 'status'], name='crm_followu_assigne_750ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['stage', 'next_followup'], name='crm_lead_stage_bdfe12_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'updated_at'], name='crm_lead_assigne_218297_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='crm_lead_phone_8180e8_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['status', 'created_at'], name='crm_quotati_status_198daa_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['customer', 'created_at'], name='crm_quotati_custome_01d7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='salesteammember',
            index=models.Index(fields=['manager', 'is_active'], name='crm_saleste_manager_e1e653_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['status', 'updated_at'], name='crm_service_status_bb2b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['customer', 'created_at'], name='crm_service_custome_582bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['assigned_to', 'status'], name='crm_service_assigne_f29e85_idx'),
        ),
        migrations.AddIndex(
            model_name='showroomvisit',
            index=models.Index(fields=['visit_at', 'status'], name='crm_showroo_visit_a_546ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='showroomvisit',
            index=models.Index(fields=['assigned_to', 'visit_at'], name='crm_showroo_assigne_19398e_idx'),
        ),
        migrations.AddIndex(
            model_name='worktask',
            index=models.Index(fields=['assigned_to', 'status', 'due_date'], name='crm_worktas_assigne_f7403f_idx'),
        ),
        migrations.AddIndex(
            model_name='worktask',
            index=models.Index(fields=['due_date', 'status'], name='crm_worktas_due_dat_3cfd7d_idx'),
        ),
    ]
